from django.urls import path

from .views import (
    dashboard_backup,
    dashboard_home,
    dashboard_module_2,
    dashboard_module_3,
    dashboard_module_4,
    dashboard_module_5,
    dashboard_module_6,
    dashboard_module_7,
    dashboard_module_8,
    dashboard_presence_json,
    dashboard_projection,
    dashboard_settings,
    dashboard_supports,
    dashboard_support_upload,
    dashboard_use_current_address,
    export_module_2_csv,
    export_module_3_csv,
    export_module_4_csv,
    export_module_5_csv,
    export_module_6_csv,
    export_module_7_csv,
    export_module_8_csv,
    home,
    module_2_form,
    module_2_success,
    module_3_form,
    module_3_success,
    module_4_form,
    module_4_success,
    module_5_form,
    module_5_success,
    module_6_form,
    module_6_success,
    module_7_form,
    module_7_success,
    module_8_form,
    module_8_success,
    network_access_dashboard,
    network_control,
    presence_heartbeat,
    support_detail,
    support_download,
    support_list,
    student_module_detail,
    student_modules,
    toggle_module_responses,
)


app_name = "surveys"

urlpatterns = [
    path("", home, name="home"),
    path("supports/", support_list, name="support_list"),
    path("supports/<slug:slug>/", support_detail, name="support_detail"),
    path("supports/<slug:slug>/download/", support_download, name="support_download"),
    path("modules/", student_modules, name="student_modules"),
    path("modules/module-2/", student_module_detail, {"module_code": "MODULE_2"}, name="student_module_2_detail"),
    path("modules/module-3/", student_module_detail, {"module_code": "MODULE_3"}, name="student_module_3_detail"),
    path("modules/module-4/", student_module_detail, {"module_code": "MODULE_4"}, name="student_module_4_detail"),
    path("modules/module-5/", student_module_detail, {"module_code": "MODULE_5"}, name="student_module_5_detail"),
    path("modules/module-6/", student_module_detail, {"module_code": "MODULE_6"}, name="student_module_6_detail"),
    path("modules/module-7/", student_module_detail, {"module_code": "MODULE_7"}, name="student_module_7_detail"),
    path("modules/module-8/", student_module_detail, {"module_code": "MODULE_8"}, name="student_module_8_detail"),
    path("module-2/", module_2_form, name="module_2"),
    path("module-2/success/<int:submission_id>/", module_2_success, name="module_2_success"),
    path("module-3/", module_3_form, name="module_3"),
    path("module-3/success/<int:submission_id>/", module_3_success, name="module_3_success"),
    path("module-4/", module_4_form, name="module_4"),
    path("module-4/success/<int:submission_id>/", module_4_success, name="module_4_success"),
    path("module-5/", module_5_form, name="module_5"),
    path("module-5/success/<int:submission_id>/", module_5_success, name="module_5_success"),
    path("module-6/", module_6_form, name="module_6"),
    path("module-6/success/<int:submission_id>/", module_6_success, name="module_6_success"),
    path("module-7/", module_7_form, name="module_7"),
    path("module-7/success/<int:submission_id>/", module_7_success, name="module_7_success"),
    path("module-8/", module_8_form, name="module_8"),
    path("module-8/success/<int:submission_id>/", module_8_success, name="module_8_success"),
    path("dashboard/", dashboard_home, name="dashboard_home"),
    path("dashboard/module-2/", dashboard_module_2, name="dashboard_module_2"),
    path("dashboard/module-3/", dashboard_module_3, name="dashboard_module_3"),
    path("dashboard/module-4/", dashboard_module_4, name="dashboard_module_4"),
    path("dashboard/module-5/", dashboard_module_5, name="dashboard_module_5"),
    path("dashboard/module-6/", dashboard_module_6, name="dashboard_module_6"),
    path("dashboard/module-7/", dashboard_module_7, name="dashboard_module_7"),
    path("dashboard/module-8/", dashboard_module_8, name="dashboard_module_8"),
    path("dashboard/export/module-2.csv", export_module_2_csv, name="export_module_2_csv"),
    path("dashboard/export/module-3.csv", export_module_3_csv, name="export_module_3_csv"),
    path("dashboard/export/module-4.csv", export_module_4_csv, name="export_module_4_csv"),
    path("dashboard/export/module-5.csv", export_module_5_csv, name="export_module_5_csv"),
    path("dashboard/export/module-6.csv", export_module_6_csv, name="export_module_6_csv"),
    path("dashboard/export/module-7.csv", export_module_7_csv, name="export_module_7_csv"),
    path("dashboard/export/module-8.csv", export_module_8_csv, name="export_module_8_csv"),
    path("dashboard/network/", network_access_dashboard, name="dashboard_network"),
    path("dashboard/network-control/", network_control, name="dashboard_network_control"),
    path("dashboard/projection/", dashboard_projection, name="dashboard_projection"),
    path("dashboard/supports/", dashboard_supports, name="dashboard_supports"),
    path("dashboard/supports/upload/", dashboard_support_upload, name="dashboard_support_upload"),
    path("dashboard/backup/", dashboard_backup, name="dashboard_backup"),
    path("dashboard/settings/", dashboard_settings, name="dashboard_settings"),
    path("dashboard/settings/use-current-address/", dashboard_use_current_address, name="dashboard_use_current_address"),
    path("dashboard/presence.json", dashboard_presence_json, name="dashboard_presence_json"),
    path("dashboard/modules/<str:module_code>/toggle-responses/", toggle_module_responses, name="toggle_module_responses"),
    path("presence/heartbeat/", presence_heartbeat, name="presence_heartbeat"),
]
