# Generated by Django 5.2.15 on 2026-06-18 08:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id_number', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2), django.core.validators.RegexValidator(message="Le numero d'identification doit contenir exactement 2 chiffres.", regex='^\\d{2}$')], verbose_name="Numero d'identification a l'ecole")),
                ('full_name', models.CharField(max_length=255, verbose_name='Nom et prenom')),
                ('class_level', models.CharField(choices=[('seconde', 'Seconde'), ('premiere', 'Premiere'), ('autre', 'Autre')], max_length=20, verbose_name='Classe / niveau')),
                ('group_name', models.CharField(blank=True, max_length=100, verbose_name='Groupe ou salle')),
            ],
            options={
                'ordering': ['school_id_number', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('trainer_name', models.CharField(max_length=255)),
                ('session_code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='surveys.trainingmodule')),
            ],
            options={
                'ordering': ['-date', 'session_code'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id_number_snapshot', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2), django.core.validators.RegexValidator(message="Le numero d'identification doit contenir exactement 2 chiffres.", regex='^\\d{2}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_eval_internet_explained', models.CharField(choices=[('pas_encore', 'Pas encore'), ('un_peu', 'Un peu'), ('bien', 'Bien'), ('tres_bien', 'Tres bien')], max_length=20)),
                ('auto_eval_learning_usage', models.CharField(choices=[('jamais', 'Jamais'), ('rarement', 'Rarement'), ('parfois', 'Parfois'), ('souvent', 'Souvent')], max_length=20)),
                ('auto_eval_open_browser', models.CharField(choices=[('non', 'Non'), ('un_peu', 'Un peu'), ('oui', 'Oui')], max_length=20)),
                ('todo_opened_browser', models.BooleanField(default=False)),
                ('todo_typed_simple_search', models.BooleanField(default=False)),
                ('todo_used_keywords', models.BooleanField(default=False)),
                ('todo_opened_result', models.BooleanField(default=False)),
                ('todo_compared_results', models.BooleanField(default=False)),
                ('todo_found_school_info', models.BooleanField(default=False)),
                ('todo_asked_for_help', models.BooleanField(default=False)),
                ('todo_noted_learning', models.BooleanField(default=False)),
                ('quiz_q1', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('quiz_q2', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('quiz_q3', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('quiz_q4_selected', models.JSONField(default=list)),
                ('quiz_q5', models.CharField(max_length=50)),
                ('practical_search_text', models.CharField(max_length=255)),
                ('practical_site_text', models.CharField(blank=True, max_length=255)),
                ('practical_subject', models.CharField(choices=[('francais', 'Francais'), ('mathematiques', 'Mathematiques'), ('sciences_physiques', 'Sciences physiques'), ('sciences_naturelles', 'Sciences naturelles'), ('anglais', 'Anglais'), ('histoire_geographie', 'Histoire-Geographie'), ('informatique', 'Informatique'), ('autre', 'Autre')], max_length=40)),
                ('feedback_understood_today', models.TextField()),
                ('feedback_still_difficult', models.TextField(blank=True)),
                ('feedback_confidence', models.CharField(choices=[('pas_encore', 'Pas encore'), ('un_peu', 'Un peu'), ('oui', 'Oui'), ('oui_beaucoup', 'Oui, beaucoup')], max_length=20)),
                ('computed_score', models.PositiveSmallIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='surveys.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='surveys.trainingsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'school_id_number_snapshot'), name='unique_submission_per_session_school_id')],
            },
        ),
    ]
