# Generated by Django 5.2.15 on 2026-06-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trainingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('module',), name='unique_active_session_per_module'),
        ),
    ]
