# Generated by Django 5.2.15 on 2026-06-22 00:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_module3submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module4Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id_number_snapshot', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2), django.core.validators.RegexValidator(message="Le numero d'identification doit contenir exactement 2 chiffres.", regex='^\\d{2}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_eval_explain_source', models.CharField(choices=[('pas_encore', 'Pas encore'), ('un_peu', 'Un peu'), ('bien', 'Bien'), ('tres_bien', 'Très bien')], max_length=20)),
                ('auto_eval_verify_info', models.CharField(choices=[('jamais', 'Jamais'), ('rarement', 'Rarement'), ('parfois', 'Parfois'), ('souvent', 'Souvent')], max_length=20)),
                ('auto_eval_spot_doubtful', models.CharField(choices=[('pas_encore', 'Pas encore'), ('un_peu', 'Un peu'), ('bien', 'Bien'), ('tres_bien', 'Très bien')], max_length=20)),
                ('todo_chose_info', models.BooleanField(default=False)),
                ('todo_opened_first_source', models.BooleanField(default=False)),
                ('todo_checked_publisher', models.BooleanField(default=False)),
                ('todo_checked_date', models.BooleanField(default=False)),
                ('todo_checked_evidence', models.BooleanField(default=False)),
                ('todo_compared_second', models.BooleanField(default=False)),
                ('todo_identified_reliable_sign', models.BooleanField(default=False)),
                ('todo_identified_doubtful_sign', models.BooleanField(default=False)),
                ('todo_decided_reliable_or_not', models.BooleanField(default=False)),
                ('todo_explained_choice', models.BooleanField(default=False)),
                ('quiz_q1', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('quiz_q2', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('quiz_q3', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('quiz_q4', models.CharField(choices=[('partager_vite', 'La partager rapidement'), ('croire_immediatement', 'La croire immédiatement'), ('verifier_autres_sources', "Vérifier avec d'autres sources"), ('ignorer_resultats', 'Ignorer tous les autres résultats')], max_length=40)),
                ('quiz_q5_selected', models.JSONField(default=list)),
                ('quiz_q6_selected', models.JSONField(default=list)),
                ('quiz_q7', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('practical_subject', models.CharField(max_length=255)),
                ('practical_first_source', models.CharField(max_length=255)),
                ('practical_publisher', models.CharField(blank=True, max_length=255)),
                ('practical_has_date', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non'), ('pas_trouve', "Je n'ai pas trouvé")], max_length=20)),
                ('practical_has_evidence', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non'), ('un_peu', 'Un peu'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('practical_compared', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5)),
                ('practical_second_source', models.CharField(blank=True, max_length=255)),
                ('practical_decision', models.CharField(choices=[('fiable', 'Plutôt fiable'), ('douteuse', 'Douteuse'), ('pas_encore', 'Je ne sais pas encore')], max_length=20)),
                ('practical_explanation', models.TextField()),
                ('feedback_understood_today', models.TextField()),
                ('feedback_still_difficult', models.TextField(blank=True)),
                ('feedback_confidence_verify', models.CharField(choices=[('pas_encore', 'Pas encore'), ('un_peu', 'Un peu'), ('oui', 'Oui'), ('oui_beaucoup', 'Oui, beaucoup')], max_length=20)),
                ('computed_score', models.PositiveSmallIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module4_submissions', to='surveys.trainingsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module4_submissions', to='surveys.student')),
            ],
            options={
                'verbose_name': 'Module 4 submission',
                'verbose_name_plural': 'Module 4 submissions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'school_id_number_snapshot'), name='unique_module4_submission_per_session_school_id')],
            },
        ),
    ]
