# Generated by Django 5.2.15 on 2026-06-22 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_module4submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(db_index=True, max_length=50)),
                ('client_id', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('current_path', models.CharField(blank=True, max_length=255)),
                ('school_id_number', models.CharField(blank=True, max_length=2, null=True)),
                ('class_level', models.CharField(blank=True, max_length=20, null=True)),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.trainingsession')),
            ],
            options={
                'verbose_name': 'Présence formulaire',
                'verbose_name_plural': 'Présences formulaires',
                'indexes': [models.Index(fields=['module_code', 'training_session', 'status'], name='surveys_for_module__c4afcc_idx'), models.Index(fields=['last_seen_at'], name='surveys_for_last_se_16a5b9_idx')],
            },
        ),
    ]
