# Generated by Django 5.2.15 on 2026-06-22 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_formpresence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpresence',
            name='last_seen_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
