# Generated by Django 5.2.15 on 2026-06-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_alter_formpresence_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='accepting_responses',
            field=models.BooleanField(default=True),
        ),
    ]
