# Generated by Django 5.2.15 on 2026-06-23 01:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_trainingsession_accepting_responses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module5Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id_number_snapshot', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2), django.core.validators.RegexValidator(message="Le numero d'identification doit contenir exactement 2 chiffres.", regex='^\\d{2}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_eval_email_purpose', models.CharField(choices=[('pas_encore', 'Pas encore'), ('un_peu', 'Un peu'), ('bien', 'Bien'), ('tres_bien', 'Très bien')], max_length=20)),
                ('auto_eval_write_email', models.CharField(choices=[('pas_encore', 'Pas encore'), ('un_peu', 'Un peu'), ('bien', 'Bien'), ('tres_bien', 'Très bien')], max_length=20)),
                ('auto_eval_attach_file', models.CharField(choices=[('pas_encore', 'Pas encore'), ('un_peu', 'Un peu'), ('bien', 'Bien'), ('tres_bien', 'Très bien')], max_length=20)),
                ('todo_spotted_recipient', models.BooleanField(default=False)),
                ('todo_written_clear_subject', models.BooleanField(default=False)),
                ('todo_started_greeting', models.BooleanField(default=False)),
                ('todo_written_short_message', models.BooleanField(default=False)),
                ('todo_added_politeness', models.BooleanField(default=False)),
                ('todo_signed_name', models.BooleanField(default=False)),
                ('todo_checked_attachment', models.BooleanField(default=False)),
                ('todo_reread_before_sending', models.BooleanField(default=False)),
                ('quiz_q1', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('quiz_q2', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('quiz_q3', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('quiz_q4', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('quiz_q5', models.CharField(choices=[('salut', 'Salut'), ('question', 'Question'), ('demande_information_devoir_mathematiques', "Demande d'information sur le devoir de mathématiques"), ('important', 'Important !!!')], max_length=50)),
                ('quiz_q6', models.CharField(choices=[('yo_prof', 'Yo prof'), ('bonjour_monsieur_madame', 'Bonjour Monsieur / Madame,'), ('eh', 'Eh'), ('reponds_vite', 'Réponds vite')], max_length=50)),
                ('quiz_q7_selected', models.JSONField(default=list)),
                ('practical_who_writing_to', models.CharField(max_length=255)),
                ('practical_email_subject', models.CharField(max_length=255)),
                ('practical_email_message', models.TextField()),
                ('practical_needs_attachment', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('practical_attachment_file', models.CharField(blank=True, max_length=255)),
                ('practical_best_tool', models.CharField(choices=[('email', 'Email'), ('facebook_public', 'Commentaire public sur Facebook'), ('message_sans_nom', 'Message sans nom'), ('tiktok', 'Publication TikTok')], max_length=40)),
                ('feedback_understood_today', models.TextField()),
                ('feedback_still_difficult', models.TextField(blank=True)),
                ('feedback_confidence_email', models.CharField(choices=[('pas_encore', 'Pas encore'), ('un_peu', 'Un peu'), ('oui', 'Oui'), ('oui_beaucoup', 'Oui, beaucoup')], max_length=20)),
                ('computed_score', models.PositiveSmallIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module5_submissions', to='surveys.trainingsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module5_submissions', to='surveys.student')),
            ],
            options={
                'verbose_name': 'Module 5 submission',
                'verbose_name_plural': 'Module 5 submissions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'school_id_number_snapshot'), name='unique_module5_submission_per_session_school_id')],
            },
        ),
    ]
