# Generated by Django 5.2.15 on 2026-06-23 01:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_module5submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module6Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id_number_snapshot', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2), django.core.validators.RegexValidator(message="Le numero d'identification doit contenir exactement 2 chiffres.", regex='^\\d{2}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_eval_find_resource', models.CharField(choices=[('pas_encore', 'Pas encore'), ('un_peu', 'Un peu'), ('bien', 'Bien'), ('tres_bien', 'Très bien')], max_length=20)),
                ('auto_eval_choose_resource', models.CharField(choices=[('pas_encore', 'Pas encore'), ('un_peu', 'Un peu'), ('bien', 'Bien'), ('tres_bien', 'Très bien')], max_length=20)),
                ('auto_eval_keep_link', models.CharField(choices=[('pas_encore', 'Pas encore'), ('un_peu', 'Un peu'), ('bien', 'Bien'), ('tres_bien', 'Très bien')], max_length=20)),
                ('todo_chose_subject', models.BooleanField(default=False)),
                ('todo_searched_resource', models.BooleanField(default=False)),
                ('todo_opened_video_pdf_exercise', models.BooleanField(default=False)),
                ('todo_checked_level', models.BooleanField(default=False)),
                ('todo_noted_resource_title', models.BooleanField(default=False)),
                ('todo_noted_link_or_site', models.BooleanField(default=False)),
                ('todo_written_what_learned', models.BooleanField(default=False)),
                ('todo_kept_for_later', models.BooleanField(default=False)),
                ('quiz_q1', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('quiz_q2', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('quiz_q3', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('quiz_q4', models.CharField(choices=[('exercice_corrige', 'Un exercice corrigé'), ('publicite', 'Une publicité'), ('rumeur', 'Une rumeur'), ('mot_de_passe', 'Un mot de passe')], max_length=40)),
                ('quiz_q5', models.CharField(choices=[('svt', 'svt'), ('photosynthese_cours_lycee_pdf', 'photosynthèse cours lycée PDF'), ('video_drole', 'vidéo drôle'), ('internet', 'internet')], max_length=50)),
                ('quiz_q6_selected', models.JSONField(default=list)),
                ('quiz_q7_selected', models.JSONField(default=list)),
                ('practical_subject', models.CharField(choices=[('francais', 'Français'), ('mathematiques', 'Mathématiques'), ('sciences_physiques', 'Sciences physiques'), ('sciences_naturelles', 'Sciences naturelles'), ('anglais', 'Anglais'), ('histoire_geographie', 'Histoire-Géographie'), ('informatique', 'Informatique'), ('autre', 'Autre')], max_length=40)),
                ('practical_what_to_revise', models.CharField(max_length=255)),
                ('practical_resource_type', models.CharField(choices=[('video', 'Vidéo'), ('pdf_fiche', 'PDF / fiche'), ('exercice_corrige', 'Exercice corrigé'), ('dictionnaire', 'Dictionnaire / traduction'), ('schema_image', 'Schéma / image'), ('quiz', 'Quiz'), ('autre', 'Autre')], max_length=40)),
                ('practical_resource_name_or_link', models.CharField(max_length=255)),
                ('practical_adapted_level', models.CharField(choices=[('oui', 'Oui'), ('un_peu', 'Un peu'), ('non', 'Non'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('practical_what_learned', models.TextField()),
                ('feedback_understood_today', models.TextField()),
                ('feedback_still_difficult', models.TextField(blank=True)),
                ('feedback_confidence_resources', models.CharField(choices=[('pas_encore', 'Pas encore'), ('un_peu', 'Un peu'), ('oui', 'Oui'), ('oui_beaucoup', 'Oui, beaucoup')], max_length=20)),
                ('computed_score', models.PositiveSmallIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module6_submissions', to='surveys.trainingsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module6_submissions', to='surveys.student')),
            ],
            options={
                'verbose_name': 'Module 6 submission',
                'verbose_name_plural': 'Module 6 submissions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'school_id_number_snapshot'), name='unique_module6_submission_per_session_school_id')],
            },
        ),
    ]
