# Generated by Django 5.2.15 on 2026-06-23 05:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_module6submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module7Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id_number_snapshot', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2), django.core.validators.RegexValidator(message="Le numero d'identification doit contenir exactement 2 chiffres.", regex='^\\d{2}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_eval_password', models.CharField(choices=[('pas_encore', 'Pas encore'), ('un_peu', 'Un peu'), ('oui', 'Oui'), ('oui_facilement', 'Oui, facilement')], max_length=20)),
                ('auto_eval_suspect', models.CharField(choices=[('pas_encore', 'Pas encore'), ('un_peu', 'Un peu'), ('oui', 'Oui'), ('oui_facilement', 'Oui, facilement')], max_length=20)),
                ('auto_eval_personal_info', models.CharField(choices=[('pas_encore', 'Pas encore'), ('un_peu', 'Un peu'), ('oui', 'Oui'), ('oui_facilement', 'Oui, facilement')], max_length=20)),
                ('todo_identified_weak_password', models.BooleanField(default=False)),
                ('todo_written_password_rules', models.BooleanField(default=False)),
                ('todo_understood_no_code_sharing', models.BooleanField(default=False)),
                ('todo_observed_suspect_message', models.BooleanField(default=False)),
                ('todo_spotted_danger_signs', models.BooleanField(default=False)),
                ('todo_applied_stop_method', models.BooleanField(default=False)),
                ('todo_listed_personal_info', models.BooleanField(default=False)),
                ('todo_ask_help', models.BooleanField(default=False)),
                ('quiz_q1', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('quiz_q2', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('quiz_q3', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('quiz_q4', models.CharField(choices=[('cliquer_tout_de_suite', 'Cliquer tout de suite'), ('partager_amis', 'Partager à tous mes amis'), ('verifier_demander_aide', "Vérifier et demander de l'aide"), ('donner_mot_de_passe', 'Donner mon mot de passe')], max_length=40)),
                ('quiz_q5_selected', models.JSONField(default=list)),
                ('quiz_q6_selected', models.JSONField(default=list)),
                ('quiz_q7_selected', models.JSONField(default=list)),
                ('practical_situation', models.CharField(choices=[('faux_message', 'Faux message'), ('lien_suspect', 'Lien suspect'), ('mot_de_passe', 'Mot de passe'), ('cyberharcelement', 'Cyberharcèlement'), ('partage_info', "Partage d'information personnelle"), ('autre', 'Autre')], max_length=30)),
                ('practical_describe', models.TextField()),
                ('practical_danger_signs', models.TextField()),
                ('practical_protect_selected', models.JSONField(default=list)),
                ('practical_good_reaction_selected', models.JSONField(default=list)),
                ('practical_explain', models.TextField()),
                ('feedback_understood_today', models.TextField()),
                ('feedback_still_difficult', models.TextField(blank=True)),
                ('feedback_confidence_security', models.CharField(choices=[('pas_encore', 'Pas encore'), ('un_peu', 'Un peu'), ('oui', 'Oui'), ('oui_beaucoup', 'Oui, beaucoup')], max_length=20)),
                ('computed_score', models.PositiveSmallIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module7_submissions', to='surveys.trainingsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module7_submissions', to='surveys.student')),
            ],
            options={
                'verbose_name': 'Module 7 submission',
                'verbose_name_plural': 'Module 7 submissions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'school_id_number_snapshot'), name='unique_module7_submission_per_session_school_id')],
            },
        ),
    ]
