# Generated by Django 5.2.15 on 2026-06-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_module7submission'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='formpresence',
            name='surveys_for_last_se_16a5b9_idx',
        ),
        migrations.AddIndex(
            model_name='formpresence',
            index=models.Index(fields=['status', 'last_seen_at'], name='surveys_for_status_a95fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='formpresence',
            index=models.Index(fields=['client_id', 'module_code', 'training_session'], name='surveys_for_client__5f5b6a_idx'),
        ),
    ]
