# Generated by Django 5.2.15 on 2026-06-24 13:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_remove_formpresence_surveys_for_last_se_16a5b9_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module8Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id_number_snapshot', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2), django.core.validators.RegexValidator(message="Le numero d'identification doit contenir exactement 2 chiffres.", regex='^\\d{2}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_eval_search', models.CharField(choices=[('pas_encore', 'Pas encore'), ('un_peu', 'Un peu'), ('bien', 'Bien'), ('tres_bien', 'Très bien')], max_length=20)),
                ('auto_eval_source', models.CharField(choices=[('pas_encore', 'Pas encore'), ('un_peu', 'Un peu'), ('bien', 'Bien'), ('tres_bien', 'Très bien')], max_length=20)),
                ('auto_eval_summarize', models.CharField(choices=[('pas_encore', 'Pas encore'), ('un_peu', 'Un peu'), ('bien', 'Bien'), ('tres_bien', 'Très bien')], max_length=20)),
                ('todo_chose_subject', models.BooleanField(default=False)),
                ('todo_written_question', models.BooleanField(default=False)),
                ('todo_transformed_keywords', models.BooleanField(default=False)),
                ('todo_found_first_source', models.BooleanField(default=False)),
                ('todo_found_second_source', models.BooleanField(default=False)),
                ('todo_checked_source_quality', models.BooleanField(default=False)),
                ('todo_chose_most_useful', models.BooleanField(default=False)),
                ('todo_noted_three_ideas', models.BooleanField(default=False)),
                ('todo_prepared_synthesis', models.BooleanField(default=False)),
                ('todo_presented_explained', models.BooleanField(default=False)),
                ('quiz_q1', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('quiz_q2', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('quiz_q3', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('quiz_q4', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('quiz_q5', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('quiz_q6', models.CharField(choices=[('vrai', 'Vrai'), ('faux', 'Faux'), ('je_ne_sais_pas', 'Je ne sais pas')], max_length=20)),
                ('quiz_q7_selected', models.JSONField(default=list)),
                ('practical_subject', models.CharField(choices=[('francais', 'Français'), ('mathematiques', 'Mathématiques'), ('sciences_physiques', 'Sciences physiques'), ('sciences_naturelles', 'Sciences naturelles'), ('anglais', 'Anglais'), ('histoire_geographie', 'Histoire-Géographie'), ('informatique', 'Informatique'), ('autre', 'Autre')], max_length=40)),
                ('practical_topic', models.CharField(max_length=255)),
                ('practical_starting_question', models.TextField()),
                ('practical_keywords_used', models.CharField(max_length=255)),
                ('practical_first_source', models.CharField(max_length=255)),
                ('practical_second_source', models.CharField(blank=True, max_length=255)),
                ('practical_verified_elements', models.JSONField(default=list)),
                ('practical_three_ideas', models.TextField()),
                ('practical_synthesis', models.TextField()),
                ('practical_academic_message', models.TextField(blank=True)),
                ('feedback_best_success', models.TextField()),
                ('feedback_still_difficult', models.TextField(blank=True)),
                ('feedback_confidence', models.CharField(choices=[('pas_encore', 'Pas encore'), ('un_peu', 'Un peu'), ('oui', 'Oui'), ('oui_beaucoup', 'Oui, beaucoup')], max_length=20)),
                ('feedback_one_thing_to_practice', models.TextField(blank=True)),
                ('computed_score', models.PositiveSmallIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module8_submissions', to='surveys.trainingsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module8_submissions', to='surveys.student')),
            ],
            options={
                'verbose_name': 'Module 8 submission',
                'verbose_name_plural': 'Module 8 submissions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'school_id_number_snapshot'), name='unique_module8_submission_per_session_school_id')],
            },
        ),
    ]
