# Generated by Django 5.2.15 on 2026-06-26 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_module8submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('audio', 'Audio'), ('other', 'Autre')], default='document', max_length=20)),
                ('module_number', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(8)])),
                ('file', models.FileField(upload_to='learning_resources/%Y/%m/')),
                ('source', models.CharField(blank=True, max_length=255)),
                ('license_label', models.CharField(blank=True, max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Support pédagogique',
                'verbose_name_plural': 'Supports pédagogiques',
                'ordering': ['module_number', 'title', '-updated_at'],
            },
        ),
    ]
