# Generated by Django 5.2.15 on 2026-08-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_module1submission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['full_name']},
        ),
        migrations.RemoveConstraint(
            model_name='module1submission',
            name='unique_module1_submission_per_session_school_id',
        ),
        migrations.RemoveConstraint(
            model_name='module3submission',
            name='unique_module3_submission_per_session_school_id',
        ),
        migrations.RemoveConstraint(
            model_name='module4submission',
            name='unique_module4_submission_per_session_school_id',
        ),
        migrations.RemoveConstraint(
            model_name='module5submission',
            name='unique_module5_submission_per_session_school_id',
        ),
        migrations.RemoveConstraint(
            model_name='module6submission',
            name='unique_module6_submission_per_session_school_id',
        ),
        migrations.RemoveConstraint(
            model_name='module7submission',
            name='unique_module7_submission_per_session_school_id',
        ),
        migrations.RemoveConstraint(
            model_name='module8submission',
            name='unique_module8_submission_per_session_school_id',
        ),
        migrations.RemoveConstraint(
            model_name='submission',
            name='unique_submission_per_session_school_id',
        ),
        migrations.RemoveField(
            model_name='formpresence',
            name='school_id_number',
        ),
        migrations.RemoveField(
            model_name='module1submission',
            name='school_id_number_snapshot',
        ),
        migrations.RemoveField(
            model_name='module3submission',
            name='school_id_number_snapshot',
        ),
        migrations.RemoveField(
            model_name='module4submission',
            name='school_id_number_snapshot',
        ),
        migrations.RemoveField(
            model_name='module5submission',
            name='school_id_number_snapshot',
        ),
        migrations.RemoveField(
            model_name='module6submission',
            name='school_id_number_snapshot',
        ),
        migrations.RemoveField(
            model_name='module7submission',
            name='school_id_number_snapshot',
        ),
        migrations.RemoveField(
            model_name='module8submission',
            name='school_id_number_snapshot',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_id_number',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='school_id_number_snapshot',
        ),
        migrations.AddConstraint(
            model_name='module1submission',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_module1_submission_per_session_student'),
        ),
        migrations.AddConstraint(
            model_name='module3submission',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_module3_submission_per_session_student'),
        ),
        migrations.AddConstraint(
            model_name='module4submission',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_module4_submission_per_session_student'),
        ),
        migrations.AddConstraint(
            model_name='module5submission',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_module5_submission_per_session_student'),
        ),
        migrations.AddConstraint(
            model_name='module6submission',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_module6_submission_per_session_student'),
        ),
        migrations.AddConstraint(
            model_name='module7submission',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_module7_submission_per_session_student'),
        ),
        migrations.AddConstraint(
            model_name='module8submission',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_module8_submission_per_session_student'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_submission_per_session_student'),
        ),
    ]
