# Generated by Django 5.2.15 on 2026-08-08 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_remove_school_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('completed', 'Modifiée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('one_time_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='surveys.trainingsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='surveys.student')),
            ],
            options={
                'verbose_name': 'Demande de modification',
                'verbose_name_plural': 'Demandes de modification',
                'ordering': ['-requested_at'],
            },
        ),
    ]
