# Generated by Django 5.2.15 on 2026-08-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_editrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='editrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('completed', 'Modifiée'), ('rejected', 'Rejetée'), ('expired', 'Expirée'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
    ]
