# Generated by Django 5.2.15 on 2026-08-12 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_editrequest_expires_at_alter_editrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkPhoneCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_url', models.URLField(max_length=255)),
                ('lan_host', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='network_phone_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test téléphone réseau',
                'verbose_name_plural': 'Tests téléphone réseau',
                'ordering': ['-checked_at'],
            },
        ),
    ]
